Repository stephendawsondev/connection-engine, pull requests merged in 2025-03, with the labels that each got.

#11 docs: update issue templates
  .github/ISSUE_TEMPLATE/epic_template.yml
  .github/ISSUE_TEMPLATE/user_story_template.yml
Labels: pull request

#20 Sd project app
  march_hackathon_placeholder/settings.py
  march_hackathon_placeholder/urls.py
  os_project/__init__.py
  os_project/admin.py
  os_project/apps.py
  os_project/forms.py
  os_project/migrations/0001_initial.py
  os_project/migrations/__init__.py
  os_project/models.py
  os_project/static/os_project/css/os_project.css
  os_project/static/os_project/js/os_project.js
  os_project/templates/os_project/express_interest.html
  os_project/templates/os_project/project_confirm_delete.html
  os_project/templates/os_project/project_dashboard.html
  os_project/templates/os_project/project_detail.html
  os_project/templates/os_project/project_form.html
  os_project/templates/os_project/project_interested_users.html
  os_project/templates/os_project/project_list.html
  os_project/tests.py
  os_project/urls.py
  os_project/views.py
  static/css/tailwind.css
  templates/base.html
Labels: pull request

#29 Sd project app
  fixtures/profiles.json
  fixtures/project_categories.json
  fixtures/project_interests.json
  fixtures/project_tags.json
  fixtures/projects.json
  fixtures/users.json
  os_project/admin.py
  os_project/decorators.py
  os_project/migrations/0002_rename_assigned_wit_id_project_old_assigned_wit_id_and_more.py
  os_project/migrations/0003_migrate_user_data.py
  os_project/models.py
  os_project/templates/os_project/project_dashboard.html
  os_project/templates/os_project/project_detail.html
  os_project/templates/os_project/project_interested_users.html
  os_project/templates/os_project/project_list.html
  os_project/views.py
  static/css/tailwind.css
  templates/base.html
Labels: enhancement, pull request

#31 Im front end
  src/styles/tailwind.css
  static/css/base.css
  static/css/tailwind.css
  templates/base.html
Labels: pull request

#32 feat: add about and team pages
  donations/migrations/0001_initial.py
  home/templates/home/team.html
  home/urls.py
  home/views.py
Labels: enhancement, pull request

#39 Added Team page and team css
  home/static/home/css/team.css
  home/templates/home/team.html
  requirements.txt
  static/css/base.css
  static/css/tailwind.css
  templates/base.html
Labels: pull request

#40 Im front end
  os_project/templates/os_project/project_list.html
  src/styles/tailwind.css
  static/css/base.css
  static/favicons/android-chrome-192x192.png
  static/favicons/android-chrome-512x512.png
  static/favicons/apple-touch-icon.png
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
  static/favicons/site.webmanifest
  templates/base.html
Labels: pull request

#42 Track and keep desired theme throughout navigation
  static/js/script.js
  templates/base.html
Labels: pull request

#43 Sd project app
  home/templates/home/home.html
  os_project/static/os_project/css/os_project.css
  os_project/static/os_project/js/os_project.js
  os_project/templates/os_project/project_detail.html
  os_project/urls.py
  os_project/views.py
  templates/base.html
  user_profile/migrations/0004_remove_os_maintainer_favourite_projects_and_more.py
  user_profile/models.py
  user_profile/static/user_profile/css/user_profile.css
  user_profile/static/user_profile/js/favorites_sidebar.js
  user_profile/templates/user_profile/sidebar_favorites.html
  user_profile/views.py
Labels: enhancement, pull request

#44 add div with logo class in the navbar + styles and urls for both dark…
  static/css/base.css
  templates/base.html
Labels: pull request

#48 Profile types
  user_profile/templates/user_profile/profile_form.html
  user_profile/views.py
Labels: pull request

#35 FIX: Session ID not pulling through - TODO - payment not pulling through
  donations/admin.py
  donations/apps.py
  donations/forms.py
  donations/migrations/0001_initial.py
  donations/migrations/0002_alter_payment_country_projectfunding_witfunding.py
  donations/migrations/0002_payment_project_payment_sponsored_user.py
  donations/migrations/0003_merge_20250323_0030.py
  donations/models.py
  donations/signals.py
  donations/static/donations/css/donations.css
  donations/static/donations/js/complete.js
  donations/static/donations/js/countryfield.js
  donations/static/donations/js/donations.js
  donations/stripe_webhook.py
  donations/templates/donations/donations.html
  donations/templates/donations/error.html
  donations/templates/donations/success.html
  donations/urls.py
  donations/views.py
  donations/webhook_handler.py
  donations/webhooks.py
  march_hackathon_placeholder/settings.py
  march_hackathon_placeholder/urls.py
  os_project/templates/os_project/project_detail.html
  os_project/views.py
  requirements.txt
  static/css/tailwind.css
  templates/base.html
Labels: pull request

#54 chore: update app name in project
  .coolify-dev/Dockerfile
  .coolify-dev/docker-compose.yml
  Procfile
  README.md
  connection_engine/__init__.py
  connection_engine/asgi.py
  connection_engine/settings.py
  connection_engine/urls.py
  connection_engine/views.py
  connection_engine/wsgi.py
  manage.py
  package-lock.json
  package.json
Labels: enhancement

#47 Added new SVGs for the github and insta links
  home/templates/home/team.html
  package-lock.json
  package.json
  static/css/tailwind.css
Labels: pull request

#58 feat: update project page to display amount of project funded
  donations/stripe_webhook.py
  donations/views.py
  fixtures/payments.json
  fixtures/project_funding.json
  fixtures/wit_funding.json
  os_project/models.py
  os_project/templates/os_project/project_detail.html
  os_project/views.py
  static/css/tailwind.css
Labels: enhancement, pull request

#61 chore: project app testing and styling changes
  home/templates/home/home.html
  os_project/forms.py
  os_project/templates/os_project/project_confirm_delete.html
  os_project/templates/os_project/project_detail.html
  os_project/templates/os_project/project_form.html
  os_project/templates/os_project/project_list.html
  os_project/views.py
  static/css/base.css
  static/css/tailwind.css
  templates/base.html
  user_profile/templates/user_profile/profile_confirm_delete.html
Labels: pull request

#60 Add email config using environment variables
  connection_engine/settings.py
  static/images/retro-star.svg
  templates/account/email/password_reset_key_message.html
  templates/account/email/password_reset_key_message.txt
  templates/account/email/password_reset_subject.txt
  templates/account/signup.html
  user_profile/adapter.py
Labels: pull request

#64 Milestone forms
  os_project/forms.py
  os_project/urls.py
  os_project/views.py
Labels: enhancement

#66 Add border to btn-outline for both dark and light theme
  static/css/base.css
Labels: pull request

#73 fix: allow country field to be blank
  donations/migrations/0004_alter_payment_country.py
  donations/models.py
Labels: bug, pull request

#75 Minor Changes in Project Pages / SignUp Form
  os_project/templates/os_project/express_interest.html
  os_project/templates/os_project/project_dashboard.html
  os_project/templates/os_project/project_detail.html
  os_project/templates/os_project/project_form.html
  os_project/templates/os_project/project_interested_users.html
  os_project/templates/os_project/project_list.html
  static/css/base.css
  user_profile/templates/user_profile/sidebar_favorites.html
Labels: pull request

#76 Navbar Styling (Colors and Icons)
  os_project/templates/os_project/manage_mentors.html
  os_project/templates/os_project/milestone_confirm_delete.html
  os_project/templates/os_project/milestone_detail.html
  os_project/templates/os_project/milestone_form.html
  os_project/templates/os_project/milestone_list.html
  os_project/templates/os_project/project_dashboard.html
  os_project/templates/os_project/project_detail.html
  os_project/templates/os_project/project_form.html
  os_project/templates/os_project/project_list.html
  static/css/base.css
  templates/base.html
  user_profile/templates/user_profile/profile_form.html
Labels: pull request

#80 Minor changes on btn styling and icon addings
  home/static/home/css/home.css
  home/templates/home/home.html
  os_project/templates/os_project/milestone_list.html
  os_project/templates/os_project/project_detail.html
  os_project/templates/os_project/project_list.html
Labels: pull request

#89 Add ilianas info to team page
  home/templates/home/team.html
Labels: pull request
